### ISSUE TITLE
是否包含progressdialog样式？

### ISSUE THREAD

**Issue by fg2q1q3q** [tianzhijiexian/EasyDialog#2]
如题

**Comment by kaleai** [comment]
本身是用progressdialog样子的，之前的版本中是有的。但是后面我还是去掉了，为什么呢？因为本身android自己就对于progressdialog有独特的设计，和alertDialog是不同的。而且它的设计有个缺陷就是不能自定义样式，因此，我就把这个功能去掉了。如果你想看有pdialog的版本，可以看下commit记录。

最后，感谢你发现了这个库！
