### ISSUE TITLE
如何自定义实现 能设定位置的dialog呢

### ISSUE THREAD

**Issue by yummyChina** [tianzhijiexian/EasyDialog#3]
我想 针对自己 实现的dialog 方便地设置具体显示位置，比如top,bottom之类的， 改如何试下呢

**Comment by kaleai** [comment]
这个库提供的是一个原生dialog的封装，仅此而已。所以如果要自定义的话可以参考这篇：http://www.cnblogs.com/tianzhijiexian/p/3867731.html

**Comment by yummyChina** [comment]
谢谢，我想尝试用原生 实现一些自定义效果，先看看你给的资料吧

**Comment by kaleai** [comment]
原生的难点就在于标准化，好处也是标准化。标准化好用，并且给用户统一的认知，坏处就是自定义能力不够，不过你可以看看我的那个资料，里面应该也比较全了。至于更复杂的效果，可能就要用别的方案啦。

**Comment by kaleai** [comment]
@yummyChina hi，我现在已经给出了一个指定显示位置的demo。是通过window来指定dialog的显示位置的一种通用方案，希望可以帮到你。
