### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by libeibei** [tianzhijiexian/EasyDialog#8]
打开开发者选项不保留活动时，dialog的点击事件没有保留。

**Comment by kaleai** [comment]
这个是没办法的事情，因为listener在恢复的时候listener没有被重新绑定。原生一直是有这样的问题的，除非强行绑定listener，这里我也想想办法吧。

**Comment by kaleai** [comment]
这个问题貌似没有什么好的解决方案，因为等于activity重新创建，除非全局静态持有监听事件，恢复的时候传入进去才行，如果此问题不严重就暂时搁置

**Comment by kaleai** [comment]
思考了一下，这个问题是无解的。dialog是会被系统恢复，但是之前绑定的事件是和activity相关的，但是那个activity已经被销毁了，所以事件肯定也就丢失了。解决的办法只有将新的activity和这个dialog重新绑定一次事件才行，具体的方案可以参考原生dialog的解决方式，这个库仅仅是封装，所以方法都是通用的。

**Comment by kaleai** [comment]
@libeibei 最新的代码中，你可以用activity来做监听器，这样就能保证不丢失了。前提是给dialog的builder设置setRetainInstance(true)
